---
title: "Práctica 1 - Clase, Objetos y Atributos"
author: "Ximena Lizeth"
format: pdf
execute: 
  echo: true
  eval: true
---

# Práctica 1: Clase, Objetos y Atributos

Una **clase** es una plantilla o molde que define cómo será un objeto.  
Un **objeto** es una instancia creada a partir de una clase.

## Ejemplo 1: Clase Persona


```{python}
class persona:
    def __init__(self, nombre, edad): # Constructor de una clase
        self.nombre = nombre
        self.edad = edad

    def presentarse(self):
        print(f"Hola, mi nombre es {self.nombre}")

    def cumplir_anios(self):
        self.edad += 1
        print(f"{self.nombre} ahora tiene {self.edad} años")

# Crear objetos (instancias de la clase)
estudiante1 = persona("Ximena", 19)
estudiante2 = persona("Cesar", 19)

estudiante1.presentarse()
estudiante2.presentarse()

estudiante1.cumplir_anios()
estudiante2.cumplir_anios()


class automovil:
    def __init__(self, marca):
        self.marca = marca

    def arrancar(self):
        print(f"{self.marca} arrancó")

# Crear un objeto
auto1 = automovil("TOYOTA")
auto1.arrancar()

class mascotas:
    def __init__(self, nombre, especie, edad, color, dueño):
        self.nombre = nombre
        self.especie = especie
        self.edad = edad
        self.color = color
        self.dueño = dueño

    def presentarse(self):
        print(f"Hola, soy {self.nombre}, una {self.especie} de color {self.color}.")
    
    def edad_act(self):
        print(f"La edad actual de {self.nombre} es de: {self.edad}")

    def cumplir_anios(self):
        self.edad += 1
        print(f"{self.nombre} ahora tiene {self.edad} años")

    def dueno_masc(self):
        print(f"El dueño de {self.nombre} es: {self.dueño}")

# Crear instancias
mascota1 = mascotas("Gord", "Chihuahua", 4, "negro", "Genesis")
mascota2 = mascotas("Roky", "Pastor Alemán", 3, "café y blanco", "Ximena")

mascota1.presentarse()
mascota1.edad_act()
mascota1.cumplir_anios()
mascota1.dueno_masc()

mascota2.presentarse()
mascota2.edad_act()
mascota2.cumplir_anios()
mascota2.dueno_masc()

